/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorLogin;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VistaLogin extends javax.swing.JFrame {
// Atributo para guardar la referencia al controlador
    private Controlador.ControladorLogin controladorLogin;
   
    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();//NO BORRAR
 
    // PANTALLA COMPLETA
    setExtendedState(JFrame.MAXIMIZED_BOTH);

    // Fondo profesional
    getContentPane().setBackground(new Color(52, 73, 94));

    // ESTILOS BRUTALES (sin tocar el layout)
    lblTitulo.setFont(new Font("Arial Black", Font.BOLD, 48));
    lblTitulo.setForeground(Color.WHITE);
    lblTitulo.setHorizontalAlignment(JLabel.CENTER); // Centrado

    jLabel1.setFont(new Font("Arial", Font.BOLD, 24));
    jLabel1.setForeground(Color.WHITE);

    lblContrasenia.setFont(new Font("Arial", Font.BOLD, 24));
    lblContrasenia.setForeground(Color.WHITE);

    txtUsuario.setFont(new Font("Arial", Font.PLAIN, 24));
    txtUsuario.setPreferredSize(new Dimension(500, 60));
    txtUsuario.setHorizontalAlignment(JTextField.CENTER);

    jPContrasenia.setFont(new Font("Arial", Font.PLAIN, 24));
    jPContrasenia.setPreferredSize(new Dimension(500, 60));
    jPContrasenia.setHorizontalAlignment(JPasswordField.CENTER);

    btnIniciarSesion.setFont(new Font("Arial Black", Font.BOLD, 28));
    btnIniciarSesion.setBackground(new Color(46, 204, 113));
    btnIniciarSesion.setForeground(Color.WHITE);
    btnIniciarSesion.setPreferredSize(new Dimension(350, 70));

    btnCerrar.setFont(new Font("Arial Black", Font.BOLD, 28));
    btnCerrar.setBackground(new Color(231, 76, 60));
    btnCerrar.setForeground(Color.WHITE);
    btnCerrar.setPreferredSize(new Dimension(350, 70));

    lblMensajeError.setFont(new Font("Arial", Font.BOLD, 22));
    lblMensajeError.setForeground(Color.RED);
    lblMensajeError.setHorizontalAlignment(JLabel.CENTER);

    // Centrar todo el panel principal (el que genera NetBeans)
    JPanel panelPrincipal = (JPanel) getContentPane();
    panelPrincipal.setLayout(new GridBagLayout());
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.gridwidth = GridBagConstraints.REMAINDER;
    gbc.anchor = GridBagConstraints.CENTER;
    gbc.insets = new Insets(20, 0, 20, 0);

    // Reagregar todos los componentes al nuevo layout
    panelPrincipal.removeAll();
    panelPrincipal.add(lblTitulo, gbc);
    panelPrincipal.add(jLabel1, gbc);
    panelPrincipal.add(txtUsuario, gbc);
    panelPrincipal.add(lblContrasenia, gbc);
    panelPrincipal.add(jPContrasenia, gbc);

    JPanel panelBotones = new JPanel();
    panelBotones.setOpaque(false);
    panelBotones.add(btnIniciarSesion);
    panelBotones.add(btnCerrar);
    panelPrincipal.add(panelBotones, gbc);

    panelPrincipal.add(lblMensajeError, gbc);

    revalidate();
    repaint();
 
     
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        lblContrasenia = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();
        jPContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Usuario");

        btnCerrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 102, 102));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(0, 102, 102));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        lblContrasenia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 102, 102));
        lblContrasenia.setText("Contraseña");

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Inicio de Sesión");

        jPContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPContraseniaActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciarSesion)
                                .addGap(94, 94, 94)
                                .addComponent(btnCerrar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTitulo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblContrasenia)
                                        .addComponent(jLabel1))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion)
                    .addComponent(btnCerrar))
                .addGap(37, 37, 37)
                .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPContraseniaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        // Pasar el foco al campo de contraseña
        jPContrasenia.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        // Obtener los valores de los campos
        String nombreUsuario = txtUsuario.getText();
        String contrasenia = new String(jPContrasenia.getPassword());

        // Validar que los campos no estén vacíos
        if (nombreUsuario.trim().isEmpty() || contrasenia.trim().isEmpty()) {
            lblMensajeError.setText("Por favor ingrese usuario y contraseña.");
            lblMensajeError.setVisible(true);
            return;
        }

        // Llamar al controlador para validar el login
        if (controladorLogin != null) {
            controladorLogin.validarCredenciales(nombreUsuario, contrasenia);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        // Llamar al controlador para cerrar la aplicación
        if (controladorLogin != null) {
            controladorLogin.cerrarAplicacion();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    
    // Método público para mostrar un mensaje de error (lo usará el controlador)
    public void mostrarMensajeError(String mensaje) {
        lblMensajeError.setText(mensaje);
        lblMensajeError.setVisible(true);
    }
    // Método público para limpiar los campos y el mensaje de error
    public void limpiarCampos() {
        txtUsuario.setText("");
        jPContrasenia.setText("");
        lblMensajeError.setVisible(false);
    }
    // Método para inyectar el controlador desde fuera
    public void establecerControlador(ControladorLogin controlador) {
        this.controladorLogin = controlador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPContrasenia;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
