/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class VistaPrimerAdmin extends javax.swing.JFrame {
    // Atributo para guardar la referencia al controlador
    private Controlador.ControladorPrimerAdmin controladorPrimerAdmin;

    /**
     * Creates new form VistaPrimerAdmin
     */
    public VistaPrimerAdmin() {
        initComponents();
    }
    // Método para inyectar el controlador desde fuera
    public void establecerControlador(Controlador.ControladorPrimerAdmin controlador) {
        this.controladorPrimerAdmin = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPrimerUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jPContrasenia = new javax.swing.JPasswordField();
        lblMensajeError = new javax.swing.JLabel();
        btnCrearPrimerAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Crear primer administrador ");

        lblPrimerUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPrimerUsuario.setForeground(new java.awt.Color(0, 102, 102));
        lblPrimerUsuario.setText("Usuario");

        lblContrasenia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 102, 102));
        lblContrasenia.setText("Contraseña");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jPContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPContraseniaActionPerformed(evt);
            }
        });

        btnCrearPrimerAdministrador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCrearPrimerAdministrador.setForeground(new java.awt.Color(0, 102, 102));
        btnCrearPrimerAdministrador.setText("Crear Primer Administrador");
        btnCrearPrimerAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPrimerAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearPrimerAdministrador)
                    .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContrasenia)
                            .addComponent(lblPrimerUsuario))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(jPContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearPrimerAdministrador)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Acción del botón "Crear Primer Administrador"
    private void btnCrearPrimerAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPrimerAdministradorActionPerformed
        // TODO add your handling code here:
    String nombreUsuario = txtUsuario.getText();
    String contrasenia = new String(jPContrasenia.getPassword());

    // Validar que los campos no estén vacíos
    if (nombreUsuario.trim().isEmpty() || contrasenia.trim().isEmpty()) {
        lblMensajeError.setText("Por favor complete todos los campos.");
        lblMensajeError.setVisible(true);
        return;
    }

    // Validar que el nombre de usuario no contenga espacios
    if (nombreUsuario.contains(" ")) {
        lblMensajeError.setText("El nombre de usuario no puede contener espacios.");
        lblMensajeError.setVisible(true);
        return;
    }

    // Llamar al controlador para crear el primer administrador
    if (controladorPrimerAdmin != null) {
        controladorPrimerAdmin.crearPrimerAdministrador(nombreUsuario, contrasenia);
    }
    }//GEN-LAST:event_btnCrearPrimerAdministradorActionPerformed
// Acción al presionar Enter en el campo de contraseña (opcional pero útil)
    private void jPContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPContraseniaActionPerformed
        // TODO add your handling code here:
         btnCrearPrimerAdministrador.doClick();
    }//GEN-LAST:event_jPContraseniaActionPerformed
// Acción al presionar Enter en el campo de usuario
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
         jPContrasenia.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    // Método público para mostrar mensajes de error (usado por el controlador)
    public void mostrarMensajeError(String mensaje) {
        lblMensajeError.setText(mensaje);
        lblMensajeError.setVisible(true);
    }
    // Si el usuario intenta cerrar la ventana con la X, salimos de la aplicación
    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrimerAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPrimerAdministrador;
    private javax.swing.JPasswordField jPContrasenia;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblPrimerUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
