/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
/**
 *
 * @author Usuario
 */
public class VistaProductosMasVendidos extends javax.swing.JFrame {
    private Controlador.ControladorProductosMasVendidos controladorProductos;
    private ChartPanel panelGrafico;

    /**
     * Creates new form VistaProductosMasVendidos
     */
    public VistaProductosMasVendidos() {
        initComponents();
    }
    // Método para inyectar el controlador desde fuera
    public void establecerControlador(Controlador.ControladorProductosMasVendidos controlador) {
        this.controladorProductos = controlador;
    }
    
    // Método para mostrar la lista de productos más vendidos en la tabla
    // MÉTODO NUEVO MUESTRA TABLA GRÁFICO DE BARRAS
     public void mostrarProductosMasVendidos(java.util.List<Modelo.ProductoMasVendidoModelo> listaProductos) {
        // Crear el modelo de la tabla
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[]{"Producto", "Cantidad Total Vendida"}, 0
        );

        // Llenar la tabla con los datos
        for (Modelo.ProductoMasVendidoModelo producto : listaProductos) {
            modelo.addRow(new Object[]{
                producto.getNombreProducto(),
                producto.getCantidadTotalVendida()
            });
        }

        // Asignar el modelo a la tabla
        tablaProductos.setModel(modelo);
        //  LLAMAR AL MÉTODO QUE CREA EL GRÁFICO
        actualizarGraficoBarras(listaProductos);
    }
     
     
     // MÉTODO CREA Y MUESTRA EL GRÁFICO DE BARRAS
    private void actualizarGraficoBarras(java.util.List<Modelo.ProductoMasVendidoModelo> listaProductos) {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Modelo.ProductoMasVendidoModelo p : listaProductos) {
            dataset.addValue(p.getCantidadTotalVendida(), "Cantidad Vendida", p.getNombreProducto());
        }

        JFreeChart chart = ChartFactory.createBarChart(
            "Productos Más Vendidos",
            "Producto",
            "Cantidad Vendida",
            dataset,
            PlotOrientation.VERTICAL,
            true, true, false
        );

        // Estilo profesional
        chart.setBackgroundPaint(new Color(40, 40, 40));
        chart.getTitle().setPaint(Color.WHITE);
        chart.getCategoryPlot().setBackgroundPaint(new Color(60, 60, 60));
        chart.getCategoryPlot().getDomainAxis().setLabelPaint(Color.WHITE);
        chart.getCategoryPlot().getRangeAxis().setLabelPaint(Color.WHITE);
        chart.getCategoryPlot().getDomainAxis().setTickLabelPaint(Color.CYAN);
        chart.getCategoryPlot().getRenderer().setSeriesPaint(0, new Color(0, 170, 255));

        // ZOOM QUE SÍ FUNCIONA EN JFreeChart 1.5.3
        ChartPanel chartPanel = new ChartPanel(chart);

        // ESTAS SON LAS LÍNEAS CORRECTAS (NO DAN ERROR)
        chartPanel.setMouseWheelEnabled(true);           // RUEDA DEL MOUSE = ZOOM
        chartPanel.setRangeZoomable(true);               // Permite zoom vertical
        chartPanel.setDomainZoomable(true);              // Permite zoom horizontal
        chartPanel.setZoomAroundAnchor(true);            // Zoom centrado en el cursor
        chartPanel.setFillZoomRectangle(true);           // Rectángulo de zoom visible
        chartPanel.setZoomFillPaint(new Color(100, 100, 255, 50)); // Color del rectángulo

        // Poner el gráfico en el scroll
        ScrollDiagramaDeBarras.setViewportView(chartPanel);
    }
    // Método para mostrar mensajes de error (si ocurre algún problema)
    private void mostrarMensajeError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ScrollTablaProductos = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnRecargar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        ScrollDiagramaDeBarras = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Productos Más Vendidos");

        ScrollTablaProductos.setForeground(new java.awt.Color(0, 102, 102));

        tablaProductos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tablaProductos.setForeground(new java.awt.Color(0, 102, 102));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Cantidad total vendida"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        ScrollTablaProductos.setViewportView(jScrollPane2);

        btnRecargar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(0, 102, 102));
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 102, 102));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(ScrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnRecargar)
                        .addGap(147, 147, 147)
                        .addComponent(btnAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(ScrollDiagramaDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(ScrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ScrollDiagramaDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnRecargar))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        // Llamar al controlador para recargar los datos desde la BD
        if (controladorProductos != null) {
          controladorProductos.cargarProductosMasVendidos();
        }
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
         // Llamar al controlador para volver al menú del administrador
        if (controladorProductos != null) {
        controladorProductos.volverAlMenu();
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProductosMasVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProductosMasVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProductosMasVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProductosMasVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProductosMasVendidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollDiagramaDeBarras;
    private javax.swing.JScrollPane ScrollTablaProductos;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
