/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class VistaMenuCajero extends javax.swing.JFrame {

    private Controlador.ControladorCajero controladorCajero;
    /**
     * Creates new form VistaMenuCajero
     */
    public VistaMenuCajero() {
        initComponents();
        
    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    pack();
        
    // Pantalla completa
    setExtendedState(JFrame.MAXIMIZED_BOTH);

    // Fondo oscuro profesional
    getContentPane().setBackground(new Color(30, 30, 40));

    //  REDISEÑO COMPLETO CON GRIDBAGLAYOUT 
    getContentPane().removeAll();  // Limpiamos el GroupLayout viejo
    getContentPane().setLayout(new GridBagLayout());

    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(20, 20, 20, 20);
    gbc.fill = GridBagConstraints.NONE;   // NO SE EXPANDEN HORIZONTALMENTE
    gbc.weightx = 0.0;                   // NO OCUPAN TODO EL ANCHO
    gbc.anchor = GridBagConstraints.CENTER; //  CENTRADOS

    // Título grande y centrado
    Titulo.setFont(new Font("Arial Black", Font.BOLD, 60));
    Titulo.setForeground(Color.WHITE);
    Titulo.setHorizontalAlignment(JLabel.CENTER);

    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 1;
    getContentPane().add(Titulo, gbc);

    // Botón Facturación (tamaño normal)
    btnFacturacion.setFont(new Font("Arial Black", Font.BOLD, 36));
    btnFacturacion.setBackground(new Color(52, 152, 219));   // Azul vibrante
    btnFacturacion.setForeground(Color.WHITE);
    btnFacturacion.setPreferredSize(new Dimension(500, 80)); //  Ancho normal
    btnFacturacion.setFocusPainted(false);

    gbc.gridy = 1;
    gbc.insets = new Insets(60, 20, 40, 20);
    getContentPane().add(btnFacturacion, gbc);

    // Botón Cerrar Sesión (tamaño normal)
    btnCerrarSesion.setFont(new Font("Arial Black", Font.BOLD, 36));
    btnCerrarSesion.setBackground(new Color(231, 76, 60));   // Rojo
    btnCerrarSesion.setForeground(Color.WHITE);
    btnCerrarSesion.setPreferredSize(new Dimension(400, 80)); // Ancho normal
    btnCerrarSesion.setFocusPainted(false);

    gbc.gridy = 2;
    gbc.insets = new Insets(20, 20, 100, 20);
    getContentPane().add(btnCerrarSesion, gbc);

    // Refrescar
    revalidate();
    repaint();
        
    }
    
    
    
    
       public void establecerControlador(Controlador.ControladorCajero controlador) {
        this.controladorCajero = controlador;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        btnFacturacion = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 102, 102));
        Titulo.setText("Menú del cajero");

        btnFacturacion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnFacturacion.setForeground(new java.awt.Color(0, 102, 102));
        btnFacturacion.setText("Realizar Factura");
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 102, 102));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacturacion)
                    .addComponent(btnCerrarSesion))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo)
                .addGap(43, 43, 43)
                .addComponent(btnFacturacion)
                .addGap(42, 42, 42)
                .addComponent(btnCerrarSesion)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
           if (controladorCajero != null) {
            controladorCajero.cerrarSesion();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        if (controladorCajero != null) {
            controladorCajero.abrirVentanaFacturacion();
        }
    }//GEN-LAST:event_btnFacturacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnFacturacion;
    // End of variables declaration//GEN-END:variables
}
