/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Usuario
 */
public class VistaPrimerAdmin extends javax.swing.JFrame {
    // Atributo para guardar la referencia al controlador
    private Controlador.ControladorPrimerAdmin controladorPrimerAdmin;

    /**
     * Creates new form VistaPrimerAdmin
     */
    public VistaPrimerAdmin() {
        initComponents();
        
// Pantalla completa
    setExtendedState(JFrame.MAXIMIZED_BOTH);

    // Fondo oscuro
    getContentPane().setBackground(new Color(70, 130, 180));

    // Limpiar layout viejo
    getContentPane().removeAll();
    getContentPane().setLayout(new GridBagLayout());

    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(20, 20, 20, 20);

    // TÍTULO 
    lblTitulo.setFont(new Font("Arial Black", Font.BOLD, 60));
    lblTitulo.setForeground(Color.WHITE);
    lblTitulo.setHorizontalAlignment(JLabel.CENTER);

    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.CENTER;
    getContentPane().add(lblTitulo, gbc);

    //  PANEL CENTRAL etiquetas a la izquierda, campos al lado
    JPanel panelFormulario = new JPanel(new GridBagLayout());
    panelFormulario.setOpaque(false);

    GridBagConstraints labelGbc = new GridBagConstraints();
    labelGbc.anchor = GridBagConstraints.EAST;   // Etiquetas alineadas a la derecha (para que queden cerca del campo)
    labelGbc.insets = new Insets(25, 50, 25, 20);
    labelGbc.weightx = 0;

    GridBagConstraints fieldGbc = new GridBagConstraints();
    fieldGbc.fill = GridBagConstraints.HORIZONTAL;
    fieldGbc.insets = new Insets(25, 0, 25, 50);
    fieldGbc.weightx = 1.0;

    // Usuario
    lblPrimerUsuario.setFont(new Font("Arial Black", Font.BOLD, 36));
    lblPrimerUsuario.setForeground(Color.WHITE);
    labelGbc.gridx = 0;
    labelGbc.gridy = 0;
    panelFormulario.add(lblPrimerUsuario, labelGbc);

    txtUsuario.setFont(new Font("Arial", Font.PLAIN, 32));
    txtUsuario.setPreferredSize(new Dimension(300, 50));
    txtUsuario.setBackground(Color.WHITE);
    fieldGbc.gridx = 1;
    fieldGbc.gridy = 0;
    panelFormulario.add(txtUsuario, fieldGbc);

    // Contraseña
    lblContrasenia.setFont(new Font("Arial Black", Font.BOLD, 36));
    lblContrasenia.setForeground(Color.WHITE);
    labelGbc.gridx = 0;
    labelGbc.gridy = 1;
    panelFormulario.add(lblContrasenia, labelGbc);

    jPContrasenia.setFont(new Font("Arial", Font.PLAIN, 32));
    jPContrasenia.setPreferredSize(new Dimension(300, 50));
    jPContrasenia.setBackground(Color.WHITE);
    fieldGbc.gridx = 1;
    fieldGbc.gridy = 1;
    panelFormulario.add(jPContrasenia, fieldGbc);

    // Agregar panel formulario al centro
    gbc.gridy = 1;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.CENTER;
    gbc.insets = new Insets(80, 0, 50, 0);
    getContentPane().add(panelFormulario, gbc);

    // MENSAJE DE ERROR 
    lblMensajeError.setFont(new Font("Arial Black", Font.BOLD, 32));
    lblMensajeError.setForeground(Color.RED);
    lblMensajeError.setHorizontalAlignment(JLabel.CENTER);
    lblMensajeError.setVisible(false);

    gbc.gridy = 2;
    gbc.insets = new Insets(0, 0, 40, 0);
    getContentPane().add(lblMensajeError, gbc);

    //  BOTÓN DE ANCHO NORMAL solo lo que ocupa el texto
    btnCrearPrimerAdministrador.setFont(new Font("Arial Black", Font.BOLD, 36));
    btnCrearPrimerAdministrador.setBackground(new Color(46, 204, 113));
    btnCrearPrimerAdministrador.setForeground(Color.WHITE);
    btnCrearPrimerAdministrador.setFocusPainted(false);
    // Sin setPreferredSize → el botón toma el tamaño natural del texto (ancho normal)

    gbc.gridy = 3;
    gbc.insets = new Insets(0, 0, 100, 0);
    gbc.anchor = GridBagConstraints.CENTER;
    getContentPane().add(btnCrearPrimerAdministrador, gbc);

    // Refrescar
    revalidate();
    repaint();
    }
    // Método para inyectar el controlador desde fuera
    public void establecerControlador(Controlador.ControladorPrimerAdmin controlador) {
        this.controladorPrimerAdmin = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPrimerUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jPContrasenia = new javax.swing.JPasswordField();
        lblMensajeError = new javax.swing.JLabel();
        btnCrearPrimerAdministrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Crear Primer Administrador ");

        lblPrimerUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblPrimerUsuario.setForeground(new java.awt.Color(0, 102, 102));
        lblPrimerUsuario.setText("Usuario");

        lblContrasenia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(0, 102, 102));
        lblContrasenia.setText("Contraseña");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jPContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPContraseniaActionPerformed(evt);
            }
        });

        btnCrearPrimerAdministrador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCrearPrimerAdministrador.setForeground(new java.awt.Color(0, 102, 102));
        btnCrearPrimerAdministrador.setText("Crear Primer Administrador");
        btnCrearPrimerAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPrimerAdministradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearPrimerAdministrador)
                    .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContrasenia)
                            .addComponent(lblPrimerUsuario))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(jPContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearPrimerAdministrador)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Acción del botón "Crear Primer Administrador"
    private void btnCrearPrimerAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPrimerAdministradorActionPerformed
        // TODO add your handling code here:
    String nombreUsuario = txtUsuario.getText();
    String contrasenia = new String(jPContrasenia.getPassword());

    // Validar que los campos no estén vacíos
    if (nombreUsuario.trim().isEmpty() || contrasenia.trim().isEmpty()) {
        lblMensajeError.setText("Por favor complete todos los campos.");
        lblMensajeError.setVisible(true);
        return;
    }

    // Validar que el nombre de usuario no contenga espacios
    if (nombreUsuario.contains(" ")) {
        lblMensajeError.setText("El nombre de usuario no puede contener espacios.");
        lblMensajeError.setVisible(true);
        return;
    }

    // Llamar al controlador para crear el primer administrador
    if (controladorPrimerAdmin != null) {
        controladorPrimerAdmin.crearPrimerAdministrador(nombreUsuario, contrasenia);
    }
    }//GEN-LAST:event_btnCrearPrimerAdministradorActionPerformed
// Acción al presionar Enter en el campo de contraseña (opcional pero útil)
    private void jPContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPContraseniaActionPerformed
        // TODO add your handling code here:
         btnCrearPrimerAdministrador.doClick();
    }//GEN-LAST:event_jPContraseniaActionPerformed
// Acción al presionar Enter en el campo de usuario
    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
         jPContrasenia.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    // Método público para mostrar mensajes de error (usado por el controlador)
    public void mostrarMensajeError(String mensaje) {
        lblMensajeError.setText(mensaje);
        lblMensajeError.setVisible(true);
    }
    // Si el usuario intenta cerrar la ventana con la X, salimos de la aplicación
    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrimerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrimerAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPrimerAdministrador;
    private javax.swing.JPasswordField jPContrasenia;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblPrimerUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
