/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class VistaMenuAdmin extends javax.swing.JFrame {
    private Controlador.ControladorAdmin controladorAdmin;
    /**
     * Creates new form VistaMenuAdmin
     */
    public VistaMenuAdmin() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // ← ESTA LÍNEA
        pack(); 
    }

    public void establecerControlador(Controlador.ControladorAdmin controlador) {
        this.controladorAdmin = controlador;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnGestionStock = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnHistorialVentas = new javax.swing.JButton();
        btnProductosMasVendidos = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Menú Del Administrador");

        btnRegistrarUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnRegistrarUsuario.setForeground(new java.awt.Color(0, 102, 102));
        btnRegistrarUsuario.setText("Registrar nuevo usuario");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });

        btnGestionStock.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGestionStock.setForeground(new java.awt.Color(0, 102, 102));
        btnGestionStock.setText("Gestión de Stock");
        btnGestionStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionStockActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 102, 102));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnHistorialVentas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnHistorialVentas.setForeground(new java.awt.Color(0, 102, 102));
        btnHistorialVentas.setText("Historial de ventas");
        btnHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialVentasActionPerformed(evt);
            }
        });

        btnProductosMasVendidos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnProductosMasVendidos.setForeground(new java.awt.Color(0, 102, 102));
        btnProductosMasVendidos.setText("Productos mas vendidos");
        btnProductosMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosMasVendidosActionPerformed(evt);
            }
        });

        btnGestionarUsuarios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGestionarUsuarios.setForeground(new java.awt.Color(0, 102, 102));
        btnGestionarUsuarios.setText("Gestionar Usuarios");
        btnGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarUsuario)
                            .addComponent(btnGestionStock)
                            .addComponent(btnHistorialVentas)
                            .addComponent(btnProductosMasVendidos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnCerrarSesion))
                            .addComponent(btnGestionarUsuarios)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblTitulo)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnRegistrarUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnGestionStock)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialVentas)
                .addGap(18, 18, 18)
                .addComponent(btnProductosMasVendidos)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarUsuarios)
                .addGap(15, 15, 15)
                .addComponent(btnCerrarSesion)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
         if (controladorAdmin != null) {
            controladorAdmin.abrirVentanaRegistrarUsuario();
        }
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnGestionStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionStockActionPerformed
        // TODO add your handling code here:
         if (controladorAdmin != null) {
            controladorAdmin.abrirVentanaGestionStock();
        }
    }//GEN-LAST:event_btnGestionStockActionPerformed

    private void btnHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentasActionPerformed
        // TODO add your handling code here:
        if (controladorAdmin != null) {
            controladorAdmin.abrirVentanaHistorialVentas();
        }
    }//GEN-LAST:event_btnHistorialVentasActionPerformed

    private void btnProductosMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosMasVendidosActionPerformed
        // TODO add your handling code here:
          if (controladorAdmin != null) {
            controladorAdmin.abrirVentanaProductosMasVendidos();
        }
    }//GEN-LAST:event_btnProductosMasVendidosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        if (controladorAdmin != null) {
            controladorAdmin.cerrarSesion();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuariosActionPerformed
        // TODO add your handling code here:
         if (controladorAdmin != null) {
        controladorAdmin.abrirVentanaGestionUsuarios();
    }
    }//GEN-LAST:event_btnGestionarUsuariosActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionStock;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JButton btnHistorialVentas;
    private javax.swing.JButton btnProductosMasVendidos;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
